import { Entry } from '../types/entry';

// Generated by scripts/generate-default-library.mjs when you want to ship
// bundled default entries in an OTA update or a new build.
export const DEFAULT_ENTRIES: Entry[] = [];
