export type AppLanguage = 'th' | 'en';

const translations = {
  en: {
    languageLabel: 'Language',
    thai: 'ไทย',
    english: 'EN',
    libraryBadge: 'LOCAL LIBRARY',
    total: 'Total',
    headerNoteTitle: 'Quick note',
    headerNoteText:
      'Add a new series, update the latest chapter, import from a spreadsheet or ZIP archive, sync OTA updates, or clear the library for a fresh upload.',
    importExcel: 'Import Excel',
    importing: 'Importing...',
    syncOta: 'Sync OTA',
    syncing: 'Syncing...',
    clearLibrary: 'Clear library',
    clearing: 'Clearing...',
    closeForm: 'Close form',
    addEntry: 'Add entry',
    appTitle: 'Comic Reading Tracker',
    appSubtitle:
      'Keep every comic in one place, track the latest chapter, and import large libraries with a cleaner workflow.',
    searchPlaceholder:
      'Search by title, chapter, or anything you want to find again',
    results: 'Results',
    entries: 'entries',
    itemsPerPage: 'Items per page',
    firstPage: 'First page',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    lastPage: 'Last page',
    pageOf: 'Page {current} of {total}',
    sortBy: 'Sort by',
    chooseSorting: 'Choose sorting',
    library: 'Library',
    noComicsSaved: 'No comics saved yet',
    noMatchingResults: 'No matching results',
    hideCompleted: 'Hide completed',
    showCompleted: 'Show completed',
    emptyDescription:
      'Start with your first entry, then come back anytime to update the latest chapter, import from Excel, or pull a new OTA library update.',
    noResultsDescription:
      'Try a different search term or change the sorting option to find what you need.',
    addFirstEntry: 'Add first entry',
    clearSearch: 'Clear search',
    loadingLibrary: 'Loading your library',
    loadingLibraryText:
      'Preparing your latest entries so you can pick up reading quickly.',
    importTitle: 'Import ',
    supportedColumnsTitle: 'Supported columns:',
    supportedColumns: ['Title', 'Cover', 'Episode', 'Latest link'],
    exampleRow: 'Example row:',
    tip: 'Tip:',
    importTipUrl:
      'Standard import only supports direct image URLs in the cover column.',
    importTipZip:
      'Tap the word Excel 4 times to unlock the special ZIP import for exported files that use `ชีต1_Images/...`.',
    importTextOnly: 'Import text only',
    importWithImageUrls: 'Import with image URLs',
    specialZipTitle: 'Special ZIP import',
    specialZipDescription:
      'Use this for your exported workbook plus the `ชีต1_Images` folder packed into the same ZIP file. The app will match image filenames directly from the archive.',
    zipTextOnly: 'ZIP import: text only',
    zipWithImages: 'ZIP import: extract cover images',
    cancel: 'Cancel',
    ok: 'OK',
    toTop: 'Top',
    editMode: 'EDIT MODE',
    newEntry: 'NEW ENTRY',
    editComicEntry: 'Edit comic entry',
    addComicEntry: 'Add comic entry',
    update: 'UPDATE',
    create: 'CREATE',
    coverImage: 'Cover image',
    clearImage: 'Clear image',
    chooseImage: 'Choose image',
    noCoverSelected: 'NO COVER SELECTED',
    noCoverSelectedText:
      'Choose an image first, or open optional links to paste a cover URL.',
    coverMissingTitle: 'NO',
    coverMissingSubtitle: 'COVER',
    optionalLinks: 'Optional links',
    showOptionalLinks: 'Show optional links',
    hideOptionalLinks: 'Hide optional links',
    savedOptionalLinks: 'Saved optional links: {count}',
    coverUrlOptional: 'Cover URL (optional)',
    titleRequired: 'Title *',
    latestChapterEpisode: 'Latest chapter / episode',
    readingLink: 'Reading link',
    saving: 'Saving...',
    saveChanges: 'Save changes',
    saveEntry: 'Save entry',
    latestChapter: 'Latest chapter',
    notSet: 'Not set',
    seriesStatus: 'Series status',
    statusOngoing: 'Ongoing',
    statusCompleted: 'Completed',
    statusDiscontinued: 'No more updates',
    openReadingLink: 'Open reading link',
    edit: 'Edit',
    delete: 'Delete',
    chooseCoverImage: 'Choose a cover image',
    imageSourceMessage: 'Where would you like to get the image from?',
    takePhoto: 'Take photo',
    chooseFromLibrary: 'Choose from library',
    deleteEntryTitle: 'Delete entry?',
    deleteEntryMessage: 'This item will be removed from your library.',
    clearLibraryTitle: 'Clear library?',
    clearLibraryMessage:
      'This will remove every comic entry from this device.',
    clearAll: 'Clear all',
    missingInformation: 'Missing information',
    photoPermissionTitle: 'Photo permission needed',
    photoPermissionMessage:
      'Please allow access so we can pick a cover image from your library.',
    cameraPermissionTitle: 'Camera permission needed',
    cameraPermissionMessage:
      'Please allow access so we can take a cover photo.',
    unableToPickImageTitle: 'Unable to pick an image',
    unableToPickImageMessage: 'The photo library could not be opened.',
    unableToTakePhotoTitle: 'Unable to take a photo',
    unableToTakePhotoMessage: 'The camera could not be opened.',
    savedTitle: 'Saved',
    savedMessage: 'This entry has been updated.',
    addedTitle: 'Added',
    addedMessage: 'Your new entry has been saved.',
    saveFailedTitle: 'Save failed',
    saveFailedMessage:
      'There was a problem while saving this entry. Please try again.',
    deleteFailedTitle: 'Delete failed',
    deleteFailedMessage: 'This entry could not be deleted.',
    libraryClearedTitle: 'Library cleared',
    libraryClearedMessage:
      'All saved entries have been removed from this device.',
    clearFailedTitle: 'Clear failed',
    clearFailedMessage: 'The library could not be cleared. Please try again.',
    chooseZipTitle: 'Please choose a ZIP file',
    chooseZipMessage:
      'This special import only accepts files ending in .zip.',
    chooseExcelTitle: 'Please choose an Excel file',
    chooseExcelMessage: 'This option only accepts .xlsx or .xls files.',
    specialZipUnlockedTitle: 'Special ZIP mode unlocked',
    specialZipUnlockedMessage:
      'You can now import a ZIP that contains the workbook and the image folder together.',
    noImportableRowsTitle: 'No importable rows found',
    noImportableRowsExcelSuffix:
      'If your cover column uses a path like `ชีต1_Images/...`, unlock the special ZIP mode instead.',
    excelImportCompleteTitle: 'Excel import complete',
    file: 'File',
    addedEntries: 'Added',
    updatedEntries: 'Updated',
    imageMode: 'Image mode',
    skipImages: 'Skip images',
    importRemoteImageUrlsOnly: 'Import remote image URLs only',
    skippedRowsWithoutTitle: 'Skipped {count} rows without a title',
    skippedCoverValues:
      'Skipped {count} cover values because they were not direct image URLs',
    importFailedTitle: 'Import failed',
    importFailedMessage:
      'This Excel file could not be read. Please make sure it is a valid .xlsx or .xls workbook.',
    syncUnavailableTitle: 'Sync unavailable in development',
    syncUnavailableMessage:
      'OTA sync only works in a built app. Expo Go and development mode always load from the dev server.',
    noUpdateFoundTitle: 'No update found',
    noUpdateFoundMessage:
      'This device is already running the latest OTA update for its current channel.',
    updateDownloadedTitle: 'Update downloaded',
    updateDownloadedMessage:
      'The latest OTA update has been downloaded. Tap OK and the app will restart into the new version.',
    syncFailedTitle: 'Sync failed',
    syncFailedMessage:
      'This build is not ready for OTA yet, or the update server could not be reached. After the next OTA-enabled build is installed, this button will start working.',
    specialZipFormatTitle: 'Special ZIP format:',
    specialZipFormat: [
      'One .xlsx or .xls workbook',
      'The image folder from your export, such as `ชีต1_Images/`',
      'Keep the original filenames so the app can match them',
    ],
    specialZipRowsSuffix:
      'We could not find any workbook rows to import from this ZIP.',
    zipFile: 'ZIP file',
    workbook: 'Workbook',
    importTextOnlyMode: 'Import text only',
    browserAttachMode: 'Attach cover images from ZIP directly in the browser',
    extractToDeviceMode: 'Extract covers from ZIP and save to this device',
    matchedCoverImages:
      'Matched {count} cover images inside the ZIP archive',
    savedCoverImages: 'Saved {count} cover images to this device',
    attachedCoverImages: 'Attached {count} cover images in this browser',
    failedToSaveCoverImages: 'Failed to save {count} cover images',
    unmatchedCoverPaths:
      'Could not match {count} cover paths from the workbook',
    largeZipNotice:
      'Large ZIP imports on web may use a lot of browser storage. If a very large library fails to persist, import on Android instead.',
    specialZipImportCompleteTitle: 'Special ZIP import complete',
    specialZipImportFailedTitle: 'Special ZIP import failed',
    specialZipImportFailedMessage:
      'We could not read that ZIP file. Make sure it contains one Excel workbook and the matching image folder.',
    androidZipReadFailedTitle: 'Could not read the selected ZIP file',
    androidZipReadFailedMessage:
      'Android could not open this file for import.',
    archiveFallbackName: 'Archive',
    fileReadError: 'Unable to read file data.',
    zipMissingWorkbookError:
      'ZIP archive does not contain an Excel workbook.',
    noLinkTitle: 'No reading link yet',
    noLinkMessage: 'This entry does not have a reading link yet.',
    cannotOpenLinkTitle: 'Unable to open link',
    cannotOpenLinkMessage:
      'This device does not support opening that link.',
    openLinkFailedTitle: 'Could not open link',
    openLinkFailedMessage:
      'There was a problem while opening the link. Please try again.',
    unknownError: 'Unknown error',
    confirmWebDelete: 'Delete this entry from your library?',
    confirmWebClear: 'Clear the entire library from this browser?',
  },
  th: {
    languageLabel: 'ภาษา',
    thai: 'ไทย',
    english: 'EN',
    libraryBadge: 'คลังในเครื่อง',
    total: 'ทั้งหมด',
    headerNoteTitle: 'โน้ตสั้น ๆ',
    headerNoteText:
      'เพิ่มเรื่องใหม่ อัปเดตตอนล่าสุด นำเข้าจากสเปรดชีตหรือ ZIP ซิงก์ OTA หรือเคลียร์คลังเพื่ออัปโหลดใหม่ได้ในที่เดียว',
    importExcel: 'นำเข้า Excel',
    importing: 'กำลังนำเข้า...',
    syncOta: 'ซิงก์ OTA',
    syncing: 'กำลังซิงก์...',
    clearLibrary: 'ล้างคลัง',
    clearing: 'กำลังล้าง...',
    closeForm: 'ปิดฟอร์ม',
    addEntry: 'เพิ่มรายการ',
    appTitle: 'ตัวติดตามการอ่านการ์ตูน',
    appSubtitle:
      'เก็บการ์ตูนทั้งหมดไว้ที่เดียว ติดตามตอนล่าสุด และนำเข้าคลังขนาดใหญ่ได้ง่ายขึ้น',
    searchPlaceholder:
      'ค้นหาจากชื่อเรื่อง ตอน หรืออะไรก็ตามที่อยากกลับมาดูอีกครั้ง',
    results: 'ผลลัพธ์',
    entries: 'รายการ',
    itemsPerPage: 'รายการต่อหน้า',
    firstPage: 'หน้าแรก',
    previousPage: 'หน้าก่อนหน้า',
    nextPage: 'หน้าถัดไป',
    lastPage: 'หน้าสุดท้าย',
    pageOf: 'หน้า {current} จาก {total}',
    sortBy: 'เรียงตาม',
    chooseSorting: 'เลือกการเรียง',
    library: 'คลังการ์ตูน',
    noComicsSaved: 'ยังไม่มีรายการการ์ตูน',
    noMatchingResults: 'ไม่พบรายการที่ค้นหา',
    hideCompleted: 'ซ่อนเรื่องที่จบแล้ว',
    showCompleted: 'แสดงเรื่องที่จบแล้ว',
    emptyDescription:
      'เริ่มเพิ่มเรื่องแรกของคุณ แล้วค่อยกลับมาอัปเดตตอนล่าสุด นำเข้าจาก Excel หรือดึง OTA รอบใหม่ภายหลัง',
    noResultsDescription:
      'ลองเปลี่ยนคำค้นหาหรือเปลี่ยนรูปแบบการเรียงเพื่อหารายการที่ต้องการ',
    addFirstEntry: 'เพิ่มเรื่องแรก',
    clearSearch: 'ล้างการค้นหา',
    loadingLibrary: 'กำลังโหลดคลังของคุณ',
    loadingLibraryText:
      'กำลังเตรียมรายการล่าสุดของคุณให้พร้อมสำหรับอ่านต่อ',
    importTitle: 'นำเข้า ',
    supportedColumnsTitle: 'คอลัมน์ที่รองรับ:',
    supportedColumns: ['ชื่อเรื่อง', 'รูปปก', 'ตอนที่', 'ลิงก์ตอนล่าสุด'],
    exampleRow: 'ตัวอย่าง 1 แถว:',
    tip: 'คำแนะนำ:',
    importTipUrl:
      'การนำเข้าแบบปกติรองรับเฉพาะลิงก์รูปโดยตรงในคอลัมน์รูปปก',
    importTipZip:
      'แตะคำว่า Excel 4 ครั้งเพื่อปลดล็อกการนำเข้า ZIP สำหรับไฟล์ที่ใช้ `ชีต1_Images/...`',
    importTextOnly: 'นำเข้าเฉพาะข้อความ',
    importWithImageUrls: 'นำเข้าพร้อมรูปจาก URL',
    specialZipTitle: 'นำเข้า ZIP พิเศษ',
    specialZipDescription:
      'ใช้กับไฟล์ workbook ที่ export ออกมาและโฟลเดอร์ `ชีต1_Images` ที่ถูกบีบรวมใน ZIP เดียวกัน แอพจะจับคู่รูปจากชื่อไฟล์ใน archive โดยตรง',
    zipTextOnly: 'ZIP: นำเข้าเฉพาะข้อความ',
    zipWithImages: 'ZIP: แตกไฟล์รูปมาด้วย',
    cancel: 'ยกเลิก',
    ok: 'ตกลง',
    toTop: 'บนสุด',
    editMode: 'โหมดแก้ไข',
    newEntry: 'รายการใหม่',
    editComicEntry: 'แก้ไขรายการการ์ตูน',
    addComicEntry: 'เพิ่มรายการการ์ตูน',
    update: 'อัปเดต',
    create: 'สร้าง',
    coverImage: 'รูปปก',
    clearImage: 'ล้างรูป',
    chooseImage: 'เลือกรูป',
    noCoverSelected: 'ยังไม่มีรูปปก',
    noCoverSelectedText: 'เลือกรูปหรือวางลิงก์รูปปกด้านล่าง',
    coverMissingTitle: 'ไม่มี',
    coverMissingSubtitle: 'รูปปก',
    coverUrlOptional: 'ลิงก์รูปปก (ถ้ามี)',
    titleRequired: 'ชื่อเรื่อง *',
    latestChapterEpisode: 'ตอนล่าสุด',
    readingLink: 'ลิงก์สำหรับอ่าน',
    saving: 'กำลังบันทึก...',
    saveChanges: 'บันทึกการแก้ไข',
    saveEntry: 'บันทึกรายการ',
    latestChapter: 'ตอนล่าสุด',
    notSet: 'ยังไม่ระบุ',
    seriesStatus: 'สถานะเรื่อง',
    statusOngoing: 'ยังไม่จบ',
    statusCompleted: 'จบแล้ว',
    statusDiscontinued: 'ไม่อัปเดตต่อ',
    openReadingLink: 'เปิดลิงก์อ่าน',
    edit: 'แก้ไข',
    delete: 'ลบ',
    chooseCoverImage: 'เลือกรูปปก',
    imageSourceMessage: 'ต้องการเลือกรูปจากที่ไหน',
    takePhoto: 'ถ่ายรูป',
    chooseFromLibrary: 'เลือกจากคลัง',
    deleteEntryTitle: 'ลบรายการนี้หรือไม่',
    deleteEntryMessage: 'รายการนี้จะถูกลบออกจากคลังของคุณ',
    clearLibraryTitle: 'ล้างคลังหรือไม่',
    clearLibraryMessage: 'การกระทำนี้จะลบรายการทั้งหมดออกจากอุปกรณ์นี้',
    clearAll: 'ล้างทั้งหมด',
    missingInformation: 'ข้อมูลยังไม่ครบ',
    photoPermissionTitle: 'ต้องการสิทธิ์เข้าถึงรูปภาพ',
    photoPermissionMessage: 'กรุณาอนุญาตเพื่อเลือกรูปจากคลังรูปภาพ',
    cameraPermissionTitle: 'ต้องการสิทธิ์กล้อง',
    cameraPermissionMessage: 'กรุณาอนุญาตเพื่อถ่ายรูปปก',
    unableToPickImageTitle: 'เลือกรูปไม่สำเร็จ',
    unableToPickImageMessage: 'ไม่สามารถเปิดคลังรูปภาพได้',
    unableToTakePhotoTitle: 'ถ่ายรูปไม่สำเร็จ',
    unableToTakePhotoMessage: 'ไม่สามารถเปิดกล้องได้',
    savedTitle: 'บันทึกสำเร็จ',
    savedMessage: 'อัปเดตรายการนี้เรียบร้อยแล้ว',
    addedTitle: 'เพิ่มสำเร็จ',
    addedMessage: 'บันทึกรายการใหม่เรียบร้อยแล้ว',
    saveFailedTitle: 'บันทึกไม่สำเร็จ',
    saveFailedMessage: 'เกิดปัญหาระหว่างบันทึกข้อมูล กรุณาลองใหม่อีกครั้ง',
    deleteFailedTitle: 'ลบไม่สำเร็จ',
    deleteFailedMessage: 'ไม่สามารถลบรายการนี้ได้',
    libraryClearedTitle: 'ล้างคลังแล้ว',
    libraryClearedMessage: 'ลบรายการทั้งหมดออกจากอุปกรณ์นี้เรียบร้อยแล้ว',
    clearFailedTitle: 'ล้างไม่สำเร็จ',
    clearFailedMessage: 'ไม่สามารถล้างคลังได้ กรุณาลองใหม่อีกครั้ง',
    chooseZipTitle: 'กรุณาเลือกไฟล์ ZIP',
    chooseZipMessage: 'โหมดนี้รับเฉพาะไฟล์ที่ลงท้ายด้วย .zip',
    chooseExcelTitle: 'กรุณาเลือกไฟล์ Excel',
    chooseExcelMessage: 'โหมดนี้รับเฉพาะไฟล์ .xlsx หรือ .xls',
    specialZipUnlockedTitle: 'ปลดล็อกโหมด ZIP พิเศษแล้ว',
    specialZipUnlockedMessage:
      'ตอนนี้คุณสามารถนำเข้า ZIP ที่มี workbook และโฟลเดอร์รูปไปพร้อมกันได้แล้ว',
    noImportableRowsTitle: 'ไม่พบแถวที่นำเข้าได้',
    noImportableRowsExcelSuffix:
      'ถ้าคอลัมน์รูปปกของคุณเป็น path แบบ `ชีต1_Images/...` ให้ปลดล็อกโหมด ZIP พิเศษแทน',
    excelImportCompleteTitle: 'นำเข้า Excel สำเร็จ',
    file: 'ไฟล์',
    addedEntries: 'เพิ่มใหม่',
    updatedEntries: 'อัปเดต',
    imageMode: 'โหมดรูปภาพ',
    skipImages: 'ไม่เอารูป',
    importRemoteImageUrlsOnly: 'นำเข้าเฉพาะ URL รูปโดยตรง',
    skippedRowsWithoutTitle: 'ข้าม {count} แถวที่ไม่มีชื่อเรื่อง',
    skippedCoverValues:
      'ข้ามค่ารูปปก {count} รายการ เพราะไม่ใช่ลิงก์รูปโดยตรง',
    importFailedTitle: 'นำเข้าไม่สำเร็จ',
    importFailedMessage:
      'ไม่สามารถอ่านไฟล์ Excel นี้ได้ กรุณาตรวจสอบว่าเป็นไฟล์ .xlsx หรือ .xls ที่ถูกต้อง',
    syncUnavailableTitle: 'ซิงก์ไม่ได้ในโหมดพัฒนา',
    syncUnavailableMessage:
      'OTA sync ใช้งานได้เฉพาะใน build จริงเท่านั้น Expo Go และโหมดพัฒนาจะโหลดจาก dev server เสมอ',
    noUpdateFoundTitle: 'ไม่พบอัปเดต',
    noUpdateFoundMessage: 'อุปกรณ์นี้ใช้ OTA ล่าสุดของ channel ปัจจุบันอยู่แล้ว',
    updateDownloadedTitle: 'ดาวน์โหลดอัปเดตแล้ว',
    updateDownloadedMessage:
      'ดาวน์โหลด OTA ล่าสุดเรียบร้อย กดตกลงแล้วแอพจะรีสตาร์ตเข้าเวอร์ชันใหม่',
    syncFailedTitle: 'ซิงก์ไม่สำเร็จ',
    syncFailedMessage:
      'build นี้อาจยังไม่พร้อมสำหรับ OTA หรือไม่สามารถเชื่อมต่อเซิร์ฟเวอร์อัปเดตได้ หลังติดตั้ง build ที่รองรับ OTA แล้วปุ่มนี้จะใช้งานได้',
    specialZipFormatTitle: 'รูปแบบ ZIP พิเศษ:',
    specialZipFormat: [
      'มี workbook .xlsx หรือ .xls 1 ไฟล์',
      'มีโฟลเดอร์รูปจากไฟล์ export เช่น `ชีต1_Images/`',
      'คงชื่อไฟล์รูปเดิมไว้เพื่อให้แอพจับคู่ได้',
    ],
    specialZipRowsSuffix: 'ไม่พบแถวใน workbook ที่สามารถนำเข้าได้จาก ZIP นี้',
    zipFile: 'ไฟล์ ZIP',
    workbook: 'Workbook',
    importTextOnlyMode: 'นำเข้าเฉพาะข้อความ',
    browserAttachMode: 'แนบรูปจาก ZIP ในเบราว์เซอร์โดยตรง',
    extractToDeviceMode: 'แตกไฟล์รูปจาก ZIP ลงอุปกรณ์นี้',
    matchedCoverImages: 'จับคู่รูปจาก ZIP ได้ {count} รายการ',
    savedCoverImages: 'บันทึกรูปลงอุปกรณ์ได้ {count} รายการ',
    attachedCoverImages: 'แนบรูปในเบราว์เซอร์ได้ {count} รายการ',
    failedToSaveCoverImages: 'บันทึกรูปไม่สำเร็จ {count} รายการ',
    unmatchedCoverPaths:
      'จับคู่ path รูปจาก workbook ไม่ได้ {count} รายการ',
    largeZipNotice:
      'การนำเข้า ZIP ขนาดใหญ่บนเว็บอาจใช้พื้นที่ browser มาก ถ้าไฟล์ใหญ่มากแนะนำให้นำเข้าบน Android แทน',
    specialZipImportCompleteTitle: 'นำเข้า ZIP พิเศษสำเร็จ',
    specialZipImportFailedTitle: 'นำเข้า ZIP พิเศษไม่สำเร็จ',
    specialZipImportFailedMessage:
      'ไม่สามารถอ่านไฟล์ ZIP นี้ได้ กรุณาตรวจสอบว่ามี workbook และโฟลเดอร์รูปที่ตรงกัน',
    androidZipReadFailedTitle: 'อ่านไฟล์ ZIP ที่เลือกไม่ได้',
    androidZipReadFailedMessage:
      'Android ไม่สามารถเปิดไฟล์นี้เพื่อนำเข้าได้',
    archiveFallbackName: 'ไฟล์ ZIP',
    fileReadError: 'ไม่สามารถอ่านข้อมูลไฟล์ได้',
    zipMissingWorkbookError: 'ไฟล์ ZIP นี้ไม่มี workbook Excel อยู่ภายใน',
    noLinkTitle: 'ยังไม่มีลิงก์',
    noLinkMessage: 'รายการนี้ยังไม่ได้ใส่ลิงก์สำหรับอ่านต่อ',
    cannotOpenLinkTitle: 'เปิดลิงก์ไม่ได้',
    cannotOpenLinkMessage: 'อุปกรณ์ไม่รองรับการเปิดลิงก์นี้',
    openLinkFailedTitle: 'เปิดลิงก์ไม่สำเร็จ',
    openLinkFailedMessage: 'เกิดปัญหาในการเปิดลิงก์ กรุณาลองใหม่',
    unknownError: 'ไม่ทราบสาเหตุ',
    confirmWebDelete: 'ลบรายการนี้ออกจากคลังหรือไม่',
    confirmWebClear: 'ล้างคลังทั้งหมดออกจาก browser นี้หรือไม่',
  },
} as const;

export const getCopy = (language: AppLanguage) => translations[language];

export const replaceCount = (template: string, count: number) =>
  template.replace('{count}', String(count));
